"""empty message

Revision ID: 451513ac0a9f
Revises: c6de52e26746
Create Date: 2024-12-01 21:01:43.522129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451513ac0a9f'
down_revision = 'c6de52e26746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('recentLoginTime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('prevLoginTime',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('prevLoginTime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('recentLoginTime',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
