"""empty message

Revision ID: c5dc891cbb8b
Revises: 9ceecdcbe05f
Create Date: 2024-11-17 22:14:14.788305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dc891cbb8b'
down_revision = '9ceecdcbe05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MFAkey', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('MFA_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('MFA_enabled')
        batch_op.drop_column('MFAkey')

    # ### end Alembic commands ###
