"""empty message

Revision ID: c6de52e26746
Revises: 709a0588b63b
Create Date: 2024-12-01 20:27:19.269484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6de52e26746'
down_revision = '709a0588b63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('latestIP',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('prevIP',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('prevIP',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('latestIP',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
